version: "3.8"

services:
  memcached:
    container_name: aws_memcached
    image: bitnami/memcached:latest
    network_mode: bridge
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_CACHE_SIZE=128
  redis:
    container_name: aws_redis
    image: bitnami/redis:latest
    network_mode: bridge
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './.redis-persistence:/bitnami/redis/data'
  localstack:
    container_name: AWS-DEVELOPMENT-WITH-LOCALSTACK
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=apigateway,s3,dynamodb,sns,sqs,firehose,kinesis,ses,sts,cloudformation,iam,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DEFAULT_REGION=us-west-2
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=1.0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=./.localstack
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
